### ISSUE TITLE
Filter unsafe inputs (better)

### ISSUE THREAD

**Issue by vzakharov** [THUDM/CogView#13]
Guys, can you do something to prohibit inputs like this one
![image](https://user-images.githubusercontent.com/188197/122180075-c7585700-ce90-11eb-8ff1-14636709e812.png)

Even worse, someone’s already trying to generate underage porn:
https://user-images.githubusercontent.com/188197/122180141-d4754600-ce90-11eb-96f6-f8cbacee8da1.mp4

Maybe add some Google-authed signup with the possibility of banning to at least make it harder for creeps to use the model for such things?

**Comment by Sleepychord** [comment]
Good reminding. Actually we already block many keywords about porn, politics, etc. but cannot eliminate them. We will consider to add some email-based registration process in the future.

**Comment by Somefive** [comment]
For CogView model, we only support simplified Chinese inputs as mentioned. The English input is not expected to receive high quality result. For Chinese inputs, we do have some restrictions for unsafe inputs but due to our limitation on resources, we do not have a very powerful filter for all mallecious inputs currently.
I agree that the given case may cause some potential misuses and should be addressed. We may update our filters according to the responses later.
Generally, the proper use for large pretraining models is an important issue. It will be addressed more in later works. Thanks for the advice.

**Comment by vzakharov** [comment]
> For CogView model, we only support simplified Chinese inputs as mentioned. The English input is not expected to receive high quality result. 

All of these are Chinese inputs, I just use Chrome’s built-in autotranslate feature to see what they mean.

**Comment by vzakharov** [comment]
@Sleepychord @Somefive you can use OpenAI’s content filter, I think it’s free to use (but you’ll still need the API key I guess): https://beta.openai.com/docs/engines/content-filter

**Comment by Somefive** [comment]
> @Sleepychord @Somefive you can use OpenAI’s content filter, I think it’s free to use (but you’ll still need the API key I guess): https://beta.openai.com/docs/engines/content-filter
That might be a good idea. We will look into it. Thanks!

**Comment by Somefive** [comment]
The OpenAI's content filter service is based on English while the CogView model takes Chinese texts as inputs so it might not be that straightforward to use their API. Instead, we employed another Chinese sensitive filter service to strengthen our input restriction now. Hope it will help alleviate this problem.
