### ISSUE TITLE
Waiting time on the demo

### ISSUE THREAD

**Issue by PapayasTehSkeletor** [THUDM/CogView#5]
Is there any way to reduce the waiting time in the demo website? I know it is working this way because people are spamming prompts, but this is a bit too much...
![image](https://user-images.githubusercontent.com/47577184/120128495-81b14400-c198-11eb-8d0e-a93dbc00187d.png)

**Comment by Somefive** [comment]
Currently, we only have limited computation resources and we deployed a request queue to handle user requests. We received an increasing number of user requests due to the release of the paper. It is hard to accelerate the processing speed in a short time but we may introduce some restrictions on user requests recently to tackle this problem. Thanks for the report.

**Comment by Somefive** [comment]
We conducted some studies for the generation time. Usually, it takes the original CogView model around 5min to generate one group of images (12 images per request). Currently, we provide 8 V100 GPUs for the services (which might change in the future as it is really expensive to do so). Therefore, we can process about 90 tasks per hour. More tasks will be waiting in queue.
At the end of May 2021, we released the paper and the website to the public, so many requests flooded into the backend service. Some overlength inputs crushed the service due to the Cuda OOM problem, which our team fixed later.
For the recent two weeks, the average number of hourly requests does not frequently exceed the throughput of our services. We expect it to run healthy for the most time now.
Some spamming requests will be blocked now as mentioned in [#13](https://github.com/THUDM/CogView/issues/13). We will be working on the improvements for the model and the service if any further enhancement is needed.

This is the monitor for the number of requests and average waiting time for the last 90 days. (Aggregated hourly.)
![image](https://user-images.githubusercontent.com/14019297/123065577-d9faff00-d441-11eb-9021-744201a0d6d4.png)
